### ISSUE TITLE
Text for Error email

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/swapbot#95] opened 2015-05-14 16:50 UTC
right now we have three emails that walk users through the process, we need an email if something goes wrong.

>Hi there!  You recently tried to place an order with Swapbot and your deposit of {Amount} {Token user tried to pay with} was rejected by the bitcoin network!  

>Don't panic! That just means you still have your {Amount} {Token user tried to pay with}, it's safely locked in your account ready for you to try again.    This can sometimes happen and has nothing at all to do with you, but it can also be caused by attempting to make a deposit with too small of a bitcoin miner fee. 

>Visit {Swapbots web address} to place your order again or email help@tokenly.com

**Comment by deweller** [comment] 2015-07-22 01:06
This error text looks specific to when a transaction was not confirmed.

Probably the most common error will be trying to purchase a token that is out of stock.

Moving this to 0.1.4 since it is dependent on #123.

**Comment by AdamBLevine** [comment] 2015-07-22 01:22
>Hi there! You recently tried to place an order with Swapbot and your deposit of {Amount} {Token user tried to pay with} has been refunded.  Why? We've run out of stock!
>
>The next time you check your wallet, you'll find your deposit {Amount} {Token user tried to pay with}, available for your use (less the .0001btc bitcoin miner fee)
> 
>Once {vending machine name and link} has been refilled you will receive an email alerting you that {token} is now available.  Sorry for the inconvenience, if you want to contact the operator {operator username} you may reply to this email.

**Comment by deweller** [comment] 2015-07-22 01:28
Instead of reply to operator, we will send a notification to the operator when a bot is out of stock.

See #8

**Comment by deweller** [comment] 2015-07-22 01:45
We will allow the user to contact the operator, but we'll need to build a web form to email the operator.  

Probably will need a CAPTCHA to prevent spam.

**Comment by deweller** [comment] 2015-08-29 13:36
Moved the "email the operator" function to a issue #185.

**Closed** 2015-08-29 17:25 UTC
Labels: enhancement
